const shadowcolor = 'rgb(145, 41, 40)'
const desctext = '#495057'
const white = 'white'
const titletext = 'rgb(145, 41, 40)'
const black = 'black'
const blue = 'blue'
const green = 'green'
const red = 'red'
const lightgray = '#ccc'
const maroon = 'rgb(145, 41, 40)'
const grey = 'grey'
export { shadowcolor, desctext, white, titletext, black, blue, green, red, lightgray, maroon, grey }